name: Развертывание, форматирование, проверка синтаксиса, выполнение миграций, загрузка фикстур, сбор статики

on:
  push:
    branches: [ master ]

jobs:
  testing:
    runs-on: ubuntu-22.04
    env:
      SECRET_KEY: 'django-insecure-s!1=txswelx%a4*i+gwgxl9i2jh1fo(-a8yf8%)e3(-*5z(xd_'
      DEBUG: 'False'
    steps:
      - name: Проверка репозитория на наличие изменений...
        uses: actions/checkout@v3

      - name: Установка и создание Python окружения...
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Установка зависимостей(requirements)...
        run: pip install -r requirements.txt

      - name: Сортировка импортов isort...
        run: isort .

      - name: Форматирование кода black...
        run: black .

      - name: Деплой...
        uses: appleboy/ssh-action@master
        with:
          host: 194.58.120.24
          username: root
          password: A+aY:%4NiYmd
          script: |
            su artem
            cd /home/artem/Site1
            git pull origin master
            echo "artem16" | sudo -S systemctl restart gunicorn

